<?php
/**
 * Danger Will Robinson, Danger. 404.
 *
 * @package davidsword-2018
 */

defined( 'ABSPATH' ) || exit;

get_header();
?>

	<!-- generated by 404.php -->

	<main>
		<section>

			<h1 class='page_title heading_404'>ERROR 404</h1>

			<div class='entry'>
				<div class='big'>
					<p>Oh no! Sorry - page not found.</p>
				</div>
				<p>
					This page was either deleted, changed,
					or improperly linked to.<br />
					Please refer to the active pages below.
				</p>
				<ul>
					<?php wp_nav_menu( 'title_li=' ); ?>
				</ul>
			</div>

		</section>
	</main>

	<!-- /generated by 404.php -->

<?php
get_footer();
