<?php
/**
 * Danger Will Robinson, Danger. 404.
 *
 * @package davidsword-ca
 */

defined( 'ABSPATH' ) || exit;

get_header();
?>

	<!-- generated by 404.php -->

	<main>
		<section>

			<h2 class='page_title heading_404'> 🥴 ERROR 404: Page not found!</h2>

			<div class='entry'>
				<p>This page was either deleted, changed, or improperly linked to.</p>
			</div>

		</section>
	</main>

	<!-- /generated by 404.php -->

<?php
get_footer();
