<?php defined('ABSPATH') || exit; get_header() ?>

	<!-- generated by archive-ramblings.php -->

	<main>
		<section>

			<div class='grid ramblings'>
				<?php get_template_part( 'partials/loop', 'ramblings' ); ?>
			</div>

			<div class='clear navigation'>
				<?= paginate_links(); ?>
			</div><!--/navigation-->

		</section>
	</main>

	<!-- /generated by archive-ramblings.php -->

<?php get_footer() ?>
