<?php defined('ABSPATH') || exit; get_header() ?>

	<!-- generated by archive-project.php -->

	<main>
		<section>

			<div class='grid projects'>

			<?php if ( have_posts() ) : while ( have_posts() ) : the_post();
			$img = wp_get_attachment_image_src( get_post_thumbnail_id( get_the_ID()), "medium" );
			?>
			<a href='<?= get_permalink() ?>'>
				<img src='<?= $img[0] ?>' />
			</a>
			<article class="<?= is_singular() ? "article_single" : "article_list" ?>">
				<strong><a href='<?= get_permalink() ?>'><?php the_title() ?></a></strong>
				<div class='entry'>
					<?php the_excerpt() ?>
				</div>
			</article>

			<?php endwhile; endif; ?>
			</div>

			<hr class='above_navigation' />

			<div class='clear navigation'>
				<?= paginate_links(); ?>
			</div><!--/navigation-->

		</section>
	</main>

	<!-- /generated by index.php -->

<?php get_footer() ?>
