<?php defined('ABSPATH') || exit; get_header() ?>

	<!-- generated by archive-project.php -->

	<main>
		<section>

			<div class='grid projects'>
				<?php get_template_part( 'partials/loop', 'projects' ); ?>
			</div>

			<div class='clear navigation'>
				<?php echo paginate_links(); ?>
			</div><!--/navigation-->

		</section>
	</main>

	<!-- /generated by archive-project.php -->

<?php get_footer() ?>
