<?php
/**
 * Archive for ART page.
 *
 * @package davidsword-2018
 */

defined( 'ABSPATH' ) || exit;

get_header();
?>

	<!-- generated by archive-art.php -->

	<main>
		<section>

			<div class='grid images'>
				<?php get_template_part( 'partials/loop', 'images' ); ?>
			</div>

			<div class='clear navigation'>
				<?php echo paginate_links(); ?>
			</div><!--/navigation-->

		</section>
	</main>

	<!-- /generated by archive-art.php -->

<?php
get_footer();
