<?php defined('ABSPATH') || exit; get_header() ?>

	<!-- generated by index.php (aka: archive-post.php) -->

	<main>
		<section>

			<div class='grid code'>
				<?php get_template_part( 'partials/loop', 'ramblings' ); ?>
			</div>

			<div class='clear navigation'>
				<?= paginate_links(); ?>
			</div><!--/navigation-->

		</section>
	</main>

	<!-- /generated by index.php -->

<?php get_footer() ?>
