<?php defined('ABSPATH') || exit; get_header() ?>

	<!-- generated by archive-project.php -->

	<main>
		<section>

			<div class='grid images'>

			<?php if ( have_posts() ) : while ( have_posts() ) : the_post();
			$img = wp_get_attachment_image_src( get_post_thumbnail_id( get_the_ID()), "medium" );
			?>
			<a href='<?= $img[0] ?>'>
				<img src='<?= $img[0] ?>' alt="<?php echo get_the_title() ?>" />
			</a>
			<?php endwhile; endif; ?>
			</div>

			<hr class='above_navigation' />

			<div class='clear navigation'>
				<?= paginate_links(); ?>
			</div><!--/navigation-->

		</section>
	</main>

	<!-- /generated by index.php -->

<?php get_footer() ?>
