<?php defined('ABSPATH') || exit; get_header() ?>

	<!-- generated by archive-images.php -->

	<main>
		<section>

			<div class='grid images'>
				<?php get_template_part( 'partials/loop', 'images' ); ?>
			</div>

			<div class='clear navigation'>
				<?= paginate_links(); ?>
			</div><!--/navigation-->

		</section>
	</main>

	<!-- /generated by archive-images.php -->

<?php get_footer() ?>
