<?php defined('ABSPATH') || exit; get_header() ?>

	<!-- generated by page.php -->

	<main>
		<section>

			<?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>

				<?php // almost never used:
				if (!($swrdbs['hero_title'] && swrdbs_has_hero())) : ?>
					<?php if (!is_front_page()) : ?>
						<!--<h1 class='page_title'><?php the_title() ?></h1>-->
					<?php endif ?>
					<?php
						$img = wp_get_attachment_image_src( get_post_thumbnail_id( get_the_ID()), 'slideshow' );
						if (!empty($img[1])) {
							echo "<img src='{$img[0]}' class='inlineFeaturedimg' />";
						}
					?>
				<?php endif ?>

				<?php if (!empty($post->post_excerpt) && !($swrdbs['hero_title'] && swrdbs_has_hero()) ) : ?>
			    <div id='excerpt'>
					<?php the_excerpt() ?>
			    </div>
			    <?php endif ?>

				<div class='entry'>
					<?php the_content() ?>
				</div>

			<?php endwhile; endif; ?>

		</section>
	</main>

	<!-- /generated by page.php -->

<?php get_footer() ?>
