<?php defined('ABSPATH') || exit; get_header() ?>

<!-- generated by page.php -->

<main>
	<section>

		<?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>

			<?php if (!empty($post->post_excerpt)) : ?>
			    <div class='excerpt'>
					<?php the_excerpt() ?>
			    </div>
		    <?php endif ?>

			<div class='entry'>
				<?php the_content() ?>
			</div>

		<?php endwhile; endif; ?>

	</section>
</main>

<!-- /generated by page.php -->

<?php get_footer() ?>
