<?php defined('ABSPATH') || exit; get_header() ?>

	<!-- generated by search.php -->

	<main>
		<section>

			<h1 class='page_title'>Search Results</h1>
			<div class='entry search_results'>

				<?php if ( have_posts() ) : while ( have_posts() ) : the_post();

					$text = get_the_excerpt();
					if (empty($text))
						$text = strip_shortcodes(strip_tags(get_the_content()));

					if (empty($text))
						$text = "";
					?>
					<div class='search_result'>
						<a class='search_result_title' href='<?= the_permalink() ?>'><?php the_title() ?></a><br />
						<a href='<?= the_permalink() ?>' class='search_result_link'><?= the_permalink() ?></a>
						<p><?= swrdbs_return_chopstring($text,150)  ?></p>
					</div>

				<?php endwhile; else : ?>
				<p style='text-align:center;padding-bottom:100px;'>No posts found. Try another keyword instead.</p>
				<?php endif; ?>

			</div><!--/entry search_results-->

		</section>
	</main>

	<!-- /generated by search.php -->

<?php get_footer() ?>
