<?php
/**
 * Search template.
 *
 * No pagination intentional. If not top result, should refined search better.
 *
 * @package davidsword-ca-custom-theme
 */

defined( 'ABSPATH' ) || exit;

get_header();

?>

	<!-- generated by search.php -->

	<main>
		<section>

			<form role="search" method="get" id="searchform" action="<?php echo esc_attr( home_url( '/' ) ); ?>">
				<input
					type="text"
					name="s"
					value="<?php echo get_search_query(); ?>"
					placeholder='Search Site...'
				/>
				<input type="submit" value="Search" />
			</form>

			<?php
			if ( have_posts() ) :
				while ( have_posts() ) :
					the_post();
					get_template_part( 'partials/article', 'search' );
				endwhile;
			else :
				get_template_part( 'partials/article', 'not-found' );
			endif;
			?>

		</section>
	</main>

	<!-- /generated by search.php -->

<?php
get_footer();
