<?php
/**
 * Single output for PROJECTS post types.
 *
 * All other post types have their own single-*.php page
 * or their single page has been deleted.
 *
 * @package davidsword-2018
 */

defined( 'ABSPATH' ) || exit;

get_header();
?>

<!-- generated by single-project.php -->

<main>
	<section>

		<?php
		if ( have_posts() ) :
			while ( have_posts() ) :
				the_post();
				?>
			<article>
				<h2>
					<span>
					<a href="/projects/">Projects</a> &raquo;
					<?php the_title(); ?>
					</span>
				</h2>

				<div class='big'>
					<?php echo the_excerpt(); ?>
				</div>

				<?php get_template_part( 'partials/inline', 'ftrimg' ); ?>

				<div class='entry'>
					<?php the_content(); ?>
				</div>

				<?php comments_template(); ?>

			</article>


			<div class='clear navigation'>
				<?php
				next_post_link( '%link', '&laquo; Prev Project' );
				previous_post_link( '%link', 'Next Project &raquo;' );
				?>
			</div><!--/navigation-->

				<?php
			endwhile;
		endif;
		?>
	</section>

</main>

<!-- /generated by single-project.php -->

<?php
get_footer();
