<?php defined('ABSPATH') || exit; get_header() ?>

<!-- generated by single.php -->

<main>
	<section>

		<?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>

			<article>
				<h2 class='single_title'>
					<span><?php the_title() ?></span>
				</h2>

				<?php if (is_singular( 'projects' )) : ?>
					<div class='excerpt'>
						<?php echo the_excerpt() ?>
					</div>
				<?php endif ?>

				<?php if (is_singular( 'post' )) : ?>
					<div class='date single_date'>
						<?= get_the_date(); ?>
					</div>
				<?php endif ?>

				<div class='entry'>
					<?php the_content() ?>
				</div>

			</article>


			<div class='clear navigation'>
				<?php
				previous_post_link('%link','&laquo; Prev', true);
				next_post_link('%link','Next &raquo;', true);
				?>
			</div><!--/navigation

		<?php endwhile; endif; ?>
	</section>

	<!--
	<section>
		<?= "<div class='clear navigation'>".paginate_links()."</div>"; ?>
	</section>
	-->

</main>

<!-- /generated by single.php -->

<?php get_footer() ?>
