<?php defined('ABSPATH') || exit; get_header() ?>

<!-- generated by single.php -->

<main>
	<section>

		<?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>

			<article>
				<h2>
					<!--
					<?php if (is_singular( 'post' )) : ?>
						<a href="<?= get_post_type_archive_link('post') ?>">Code</a> &raquo;
					<?php endif ?>
					-->
					<span><?php the_title() ?></span>
				</h2>

				<?php if (is_singular( 'projects' )) : ?>
					<div class='excerpt'>
						<?php echo the_excerpt() ?>
					</div>
				<?php endif ?>

				<?php if (is_singular( 'post' )) : ?>
					<div class='postMeta'>
						<div class='postMeta--date postMeta--single-date'>
							<?= get_the_date(); ?>
						</div>
						<div class='postMeta--tags'>
							<?php
							$terms = wp_get_post_terms( get_the_ID(), 'category' );
							foreach ($terms as $term) {
								$link = get_term_link($term->term_id,'category');
								?>
								<a href='<?= $link ?>'>#<?= $term->name ?></a>
								<?php
							}
							?>
						</div>
					</div>
				<?php endif ?>

				<?php get_template_part( 'partials/inline', 'ftrimg' ); ?>

				<div class='entry'>
					<?php the_content() ?>
				</div>

				<?php
				// If comments are open or we have at least one comment, load up the comment template.
				if ( comments_open() || get_comments_number() ) :
					comments_template();
				endif;
				?>

			</article>


			<div class='clear navigation'>
				<?php
				next_post_link('%link','&laquo; Prev');
				previous_post_link('%link','Next &raquo;');
				?>
			</div><!--/navigation-->



		<?php endwhile; endif; ?>
	</section>

</main>

<!-- /generated by single.php -->

<?php get_footer() ?>
