<?php defined('ABSPATH') || exit; get_header() ?>

<!-- generated by single.php -->

<main>
	<section>

		<?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>

			<article>
				<h2>
					<a href="<?= get_post_type_archive_link('ramblings') ?>">Ramblings</a> &raquo; <span><?= get_the_date(); ?></span>
				</h2>

				<?php get_template_part( 'partials/inline', 'ftrimg' ); ?>

				<div class='entry'>
					<?php the_content(); ?>
				</div>

			</article>

			<div class='clear navigation'>
				<?php
				previous_post_link('%link','&laquo; Prev');
				next_post_link('%link','Next &raquo;');
				?>
			</div><!--/navigation-->

		<?php endwhile; endif; ?>
	</section>

</main>

<!-- /generated by single.php -->

<?php get_footer() ?>
